# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: flickrGal
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A clean, easy to use gallery that pulls specified image collections from a given flikr account.
  flickerGal hooks into the flikr api, in pure javascript with no external dependancies. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: FanninMatt
github_username:  bluefantail

# Build settings
markdown: kramdown
